version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do container para a porta 3000 da m치quina host
    volumes:
      - .:/app  # Mapeia o diret칩rio atual para o diret칩rio /app dentro do container
    environment:
      - NODE_ENV=development  # Configura a vari치vel de ambiente para desenvolvimento
    command: npm run dev  # Comando para iniciar o Next.js em modo de desenvolvimento
